const JOBS = [
  { name: "EVA Engineer", type: "Physical", cal: 4500 },
  { name: "Construction Specialist", type: "Physical", cal: 4500 },
  { name: "Security Officer", type: "Security", cal: 3000 },
  
  { name: "Technician", type: "Technical", cal: 2500 },
  { name: "Robotics Mechanic", type: "Technical", cal: 2600 },
  
  { name: "Medical Officer", type: "Cognitive", cal: 2500 },
  { name: "AI Systems Operator", type: "Cognitive", cal: 2750 },
  
  { name: "Pilot / Navigator", type: "Navigation", cal: 3000 },
  { name: "Hydroponics Farmer", type: "Navigation", cal: 3000 },
  
  { name: "Chef / Nutrition Designer", type: "Social", cal: 3500 },
  { name: "Ship Teacher", type: "Social", cal: 4000 }
];

const RECIPES=[
  {flag:"🇮🇳",name:"Butter Chicken",origin:"India",tags:["lab-grown chicken","hydroponic tomatoes","synthetic dairy","algae oil","garlic","onions"],why:"High morale meal. Strong cultural value. Protein-rich.",pro:8,carb:4,fat:7,vit:6,mealTypes:["lunch","dinner"]},
  {flag:"🇮🇳",name:"Dal Tadka",origin:"India",tags:["lentils","fermented soy paste","onions","garlic","yeast cultures","spices"],why:"Sustainable lentil base. Excellent plant protein and fibre.",pro:7,carb:7,fat:3,vit:7,mealTypes:["breakfast","lunch","dinner"]},
  {flag:"🇮🇳",name:"Masala Oats",origin:"India",tags:["oats","onions","hydroponic tomatoes","garlic","yeast cultures"],why:"High-satiety breakfast, sustained energy release.",pro:5,carb:8,fat:3,vit:7,mealTypes:["breakfast"]},
  {flag:"🇮🇳",name:"Chana Masala",origin:"India",tags:["chickpeas","hydroponic tomatoes","onions","garlic","bell peppers","spices"],why:"Iron and fibre powerhouse. Fully plant-based, zero waste.",pro:8,carb:7,fat:3,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇮🇳",name:"Khichdi",origin:"India",tags:["rice cultures","lentils","onions","garlic","seeds","yeast cultures"],why:"The original recovery meal. Easy digestion post-shift.",pro:7,carb:8,fat:2,vit:7,mealTypes:["breakfast","lunch","dinner"]},
  {flag:"🇯🇵",name:"Ramen",origin:"Japan",tags:["algae noodles","synthetic egg protein","seaweed sheets","fungal broth"],why:"Efficient ingredients + comforting warmth.",pro:7,carb:7,fat:4,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇯🇵",name:"Onigiri",origin:"Japan",tags:["rice cultures","seaweed sheets","fermented soy paste","seeds"],why:"Compact, portable, high morale.",pro:4,carb:9,fat:2,vit:5,mealTypes:["breakfast","lunch"]},
  {flag:"🇯🇵",name:"Miso Soup & Rice",origin:"Japan",tags:["fermented soy paste","seaweed sheets","rice cultures","mushrooms","yeast cultures"],why:"Probiotic-rich. Gut health critical on long voyages.",pro:5,carb:8,fat:2,vit:8,mealTypes:["breakfast","lunch"]},
  {flag:"🇯🇵",name:"Tofu Teriyaki Bowl",origin:"Japan",tags:["soybeans","fermented soy paste","rice cultures","seaweed sheets","seeds","algae oil"],why:"Complete amino acids from soy. Algae oil boosts omega-3.",pro:8,carb:7,fat:5,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇲🇽",name:"Tacos",origin:"Mexico",tags:["insect protein tortillas","lentils","lab-grown chicken","hydroponic vegetables"],why:"Flexible recipe using minimal resources.",pro:9,carb:6,fat:4,vit:7,mealTypes:["lunch","dinner"]},
  {flag:"🇲🇽",name:"Black Bean Burrito",origin:"Mexico",tags:["soybeans","rice cultures","hydroponic lettuce","fermented soy paste","bell peppers"],why:"Dense calorie and protein payload for heavy-duty crews.",pro:8,carb:8,fat:3,vit:6,mealTypes:["lunch","dinner"]},
  {flag:"🇲🇽",name:"Pozole de Hongos",origin:"Mexico",tags:["mycoprotein fungi","hydroponic vegetables","onions","garlic","herbs","bell peppers"],why:"Traditional stew adapted. Fungi = sustainable protein.",pro:7,carb:7,fat:3,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇬🇧",name:"Shepherd's Pie",origin:"United Kingdom",tags:["hydroponic potatoes","mycoprotein fungi","algae oil","onions","garlic"],why:"Dense calories for physical workers.",pro:7,carb:8,fat:5,vit:6,mealTypes:["dinner"]},
  {flag:"🇬🇧",name:"Porridge & Seeds",origin:"United Kingdom",tags:["oats","seeds","fruit cell cultures","yeast cultures"],why:"Slow-release energy. Ideal pre-shift morning meal.",pro:5,carb:8,fat:5,vit:7,mealTypes:["breakfast"]},
  {flag:"🇬🇧",name:"Lentil Cottage Pie",origin:"United Kingdom",tags:["lentils","hydroponic potatoes","mushrooms","onions","garlic"],why:"100% plant-based. Zero waste. High protein efficiency.",pro:8,carb:8,fat:2,vit:7,mealTypes:["lunch","dinner"]},
  {flag:"🇰🇷",name:"Bibimbap",origin:"South Korea",tags:["rice cultures","hydroponic greens","synthetic egg protein","fermented soy paste"],why:"Balanced nutrition in one bowl.",pro:7,carb:8,fat:5,vit:9,mealTypes:["lunch","dinner"]},
  {flag:"🇰🇷",name:"Kimchi Fried Rice",origin:"South Korea",tags:["rice cultures","fermented soy paste","synthetic egg protein","seaweed sheets","yeast cultures"],why:"Fermented foods support gut microbiome in zero-G.",pro:6,carb:8,fat:4,vit:8,mealTypes:["breakfast","lunch"]},
  {flag:"🇰🇷",name:"Sundubu Jjigae",origin:"South Korea",tags:["soybeans","mushrooms","hydroponic greens","seaweed sheets","fermented soy paste","synthetic egg protein"],why:"Silken tofu stew. High protein, anti-inflammatory.",pro:8,carb:4,fat:5,vit:9,mealTypes:["breakfast","lunch","dinner"]},
  {flag:"🇮🇹",name:"Margherita Pizza",origin:"Italy",tags:["algae flour crust","hydroponic tomatoes","synthetic dairy","herbs"],why:"Massive morale booster and social food.",pro:6,carb:8,fat:6,vit:7,mealTypes:["lunch","dinner"]},
  {flag:"🇮🇹",name:"Pasta e Fagioli",origin:"Italy",tags:["lentils","chickpeas","fermented soy paste","onions","garlic","seaweed sheets"],why:"Complete amino acid profile. Low resource cost.",pro:8,carb:8,fat:2,vit:7,mealTypes:["lunch","dinner"]},
  {flag:"🇮🇹",name:"Risotto ai Funghi",origin:"Italy",tags:["rice cultures","mycoprotein fungi","synthetic dairy","yeast cultures","onions","algae oil"],why:"Warming comfort food. Fungi = low-impact protein.",pro:6,carb:8,fat:6,vit:7,mealTypes:["dinner"]},
  {flag:"🇻🇳",name:"Pho",origin:"Vietnam",tags:["algae broth","rice cultures","hydroponic herbs","cultured beef strips"],why:"Hydrating and efficient.",pro:7,carb:7,fat:3,vit:9,mealTypes:["breakfast","lunch","dinner"]},
  {flag:"🇻🇳",name:"Bánh Mì Bowl",origin:"Vietnam",tags:["insect protein flour","fermented soy paste","hydroponic lettuce","rice cultures"],why:"Street-food efficiency. High morale from complex flavours.",pro:8,carb:7,fat:4,vit:7,mealTypes:["lunch"]},
  {flag:"�🇹",name:"Falafel Wraps",origin:"Middle East",tags:["chickpeas","algae flatbread","hydroponic lettuce","herbs","garlic"],why:"Cheap, sustainable protein source.",pro:8,carb:7,fat:4,vit:6,mealTypes:["lunch","dinner"]},
  {flag:"🇪🇹",name:"Shakshuka",origin:"North Africa",tags:["hydroponic tomatoes","synthetic egg protein","onions","garlic","bell peppers","spices"],why:"Iron-rich, anti-inflammatory. Excellent crew wellness food.",pro:7,carb:5,fat:5,vit:9,mealTypes:["breakfast","lunch"]},
  {flag:"�🇹",name:"Hummus & Flatbread",origin:"Middle East",tags:["chickpeas","algae oil","garlic","algae flatbread","seeds"],why:"High-fibre snack. Excellent calcium source.",pro:6,carb:7,fat:6,vit:6,mealTypes:["breakfast","lunch"]},
  {flag:"🇲🇦",name:"Tagine de Lentilles",origin:"Morocco",tags:["lentils","hydroponic tomatoes","onions","garlic","sweet potatoes","spices"],why:"North African spice blend fights inflammation. Dense nutrients.",pro:8,carb:8,fat:2,vit:9,mealTypes:["lunch","dinner"]},
  {flag:"🇪🇬",name:"Koshari",origin:"Egypt",tags:["rice cultures","lentils","chickpeas","onions","hydroponic tomatoes","garlic"],why:"Three complete proteins in one bowl.",pro:8,carb:9,fat:2,vit:7,mealTypes:["lunch","dinner"]},
  {flag:"🇨🇳",name:"Fried Rice",origin:"China",tags:["rice cultures","synthetic egg protein","hydroponic vegetables","fermented soy paste"],why:"Uses leftovers efficiently with minimal waste.",pro:6,carb:8,fat:4,vit:6,mealTypes:["breakfast","lunch","dinner"]},
  {flag:"🇨🇳",name:"Congee",origin:"China",tags:["rice cultures","seaweed sheets","fermented soy paste","mushrooms"],why:"Ultra light, restorative. Ideal for recovery days.",pro:4,carb:8,fat:1,vit:7,mealTypes:["breakfast"]},
  {flag:"🇨🇳",name:"Mapo Tofu",origin:"China",tags:["soybeans","mycoprotein fungi","fermented soy paste","onions","garlic","algae oil"],why:"Complete protein. Spiced oil aids circulation on long shifts.",pro:9,carb:3,fat:6,vit:7,mealTypes:["lunch","dinner"]},
  {flag:"🇨🇦",name:"Poutine",origin:"Canada",tags:["hydroponic potato fries","synthetic dairy curds","mycoprotein gravy"],why:"Comfort food during morale crises.",pro:5,carb:9,fat:6,vit:4,mealTypes:["lunch","dinner"]},
  {flag:"🇪🇹",name:"Injera & Lentil Stew",origin:"Ethiopia",tags:["lentils","fermented soy paste","onions","garlic","bell peppers","yeast cultures"],why:"Fermented injera feeds gut biome. Lentils = zero-waste protein.",pro:8,carb:7,fat:2,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇪🇹",name:"Tibs Fitfit",origin:"Ethiopia",tags:["lab-grown chicken","fermented soy paste","onions","garlic","bell peppers","herbs"],why:"Protein-packed celebration dish. Community morale booster.",pro:9,carb:4,fat:5,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇬🇷",name:"Greek Quinoa Bowl",origin:"Greece",tags:["quinoa","hydroponic tomatoes","synthetic dairy","algae oil","hydroponic herbs"],why:"Complete protein from quinoa. Mediterranean longevity diet.",pro:7,carb:7,fat:6,vit:9,mealTypes:["breakfast","lunch"]},
  {flag:"🇵🇪",name:"Quinoa Stew",origin:"Peru",tags:["quinoa","soybeans","sweet potatoes","onions","garlic","seeds"],why:"Andean superfood combo. Excellent for high-demand crew.",pro:8,carb:8,fat:4,vit:9,mealTypes:["lunch","dinner"]},
  {flag:"🇵🇪",name:"Causa Rellena",origin:"Peru",tags:["hydroponic potatoes","lentils","algae oil","hydroponic lettuce","onions"],why:"Layered potato terrine. High-density carb for physical labour.",pro:6,carb:9,fat:4,vit:7,mealTypes:["lunch","dinner"]},
  {flag:"🇳🇬",name:"Jollof Rice & Beans",origin:"Nigeria",tags:["rice cultures","soybeans","hydroponic tomatoes","onions","bell peppers"],why:"Culturally iconic across Africa. High morale from familiarity.",pro:7,carb:8,fat:3,vit:7,mealTypes:["lunch","dinner"]},
  {flag:"🇳🇬",name:"Egusi Soup",origin:"Nigeria",tags:["seeds","soybeans","hydroponic greens","onions","mushrooms","algae oil"],why:"Melon seeds = extremely high fat and protein density.",pro:8,carb:4,fat:9,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇧🇷",name:"Feijão Tropeiro",origin:"Brazil",tags:["soybeans","rice cultures","synthetic egg protein","garlic","onions"],why:"Calorie-dense cowboy meal. Excellent for physical labour.",pro:8,carb:8,fat:4,vit:6,mealTypes:["lunch","dinner"]},
  {flag:"🇹🇭",name:"Green Curry",origin:"Thailand",tags:["mycoprotein fungi","algae milk","hydroponic vegetables","rice cultures","herbs"],why:"Anti-inflammatory spices. Flavour complexity lifts morale.",pro:6,carb:7,fat:7,vit:9,mealTypes:["lunch","dinner"]},
  {flag:"🇹🇭",name:"Tom Yum Broth",origin:"Thailand",tags:["algae broth","mushrooms","lemongrass","hydroponic herbs","synthetic egg protein"],why:"Hydrating immunity broth. Lemongrass combats space fatigue.",pro:5,carb:3,fat:3,vit:10,mealTypes:["breakfast","lunch","dinner"]},
  {flag:"🇺🇸",name:"Protein Power Bowl",origin:"USA",tags:["insect protein flour","sweet potatoes","seeds","kale","algae oil"],why:"Designed for max performance. High protein density per gram.",pro:9,carb:7,fat:6,vit:9,mealTypes:["breakfast","lunch"]},
  {flag:"🇪🇸",name:"Vegetable Paella",origin:"Spain",tags:["rice cultures","bell peppers","onions","mushrooms","garlic","algae oil"],why:"Communal dish — crew social bonding meal.",pro:5,carb:9,fat:4,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇮🇷",name:"Ash Reshteh",origin:"Iran",tags:["lentils","chickpeas","soybeans","algae noodles","onions","herbs","yeast cultures"],why:"Thick Persian herb noodle soup. Rich in plant iron and folate.",pro:8,carb:8,fat:2,vit:9,mealTypes:["lunch","dinner"]},
  {flag:"🇬🇭",name:"Red Red",origin:"Ghana",tags:["soybeans","sweet potatoes","onions","bell peppers","algae oil","hydroponic tomatoes"],why:"Black-eyed bean stew. Essential B-vitamins for nerve health.",pro:8,carb:7,fat:4,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇵🇭",name:"Sinigang na Gulay",origin:"Philippines",tags:["hydroponic vegetables","soybeans","mushrooms","onions","algae broth","garlic"],why:"Sour tamarind broth. Vitamin C boosts immune function.",pro:6,carb:5,fat:3,vit:10,mealTypes:["lunch","dinner"]},
  {flag:"🇹🇷",name:"Mercimek Çorbası",origin:"Turkey",tags:["lentils","onions","garlic","hydroponic tomatoes","algae oil","spices"],why:"Red lentil soup. Simple, low-waste, high-iron.",pro:8,carb:7,fat:3,vit:8,mealTypes:["breakfast","lunch","dinner"]},
  {flag:"🇯🇲",name:"Ackee & Protein Hash",origin:"Jamaica",tags:["soybeans","hydroponic tomatoes","onions","bell peppers","algae oil","synthetic egg protein"],why:"Cultural staple reimagined. Unique Caribbean nutrient profile.",pro:7,carb:5,fat:7,vit:8,mealTypes:["breakfast","lunch"]},
  {flag:"🇦🇷",name:"Locro Stew",origin:"Argentina",tags:["chickpeas","sweet potatoes","onions","garlic","bell peppers","seeds"],why:"Thick winter stew. Dense calories for extreme physical work.",pro:7,carb:8,fat:4,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇮🇩",name:"Nasi Goreng",origin:"Indonesia",tags:["rice cultures","synthetic egg protein","soybeans","fermented soy paste","garlic","onions"],why:"Indonesia's comfort food. High morale, highly adaptable.",pro:7,carb:8,fat:5,vit:7,mealTypes:["breakfast","lunch","dinner"]},
  {flag:"🇺🇦",name:"Borscht",origin:"Ukraine",tags:["hydroponic tomatoes","soybeans","onions","garlic","mushrooms","yeast cultures"],why:"Simulated beetroot base rich in nitrates. Boosts circulation.",pro:6,carb:6,fat:2,vit:10,mealTypes:["lunch","dinner"]},
  {flag:"🇸🇳",name:"Thieboudienne Bowl",origin:"Senegal",tags:["rice cultures","cultured fish cells","hydroponic tomatoes","onions","bell peppers","algae oil"],why:"West Africa's favourite rice-fish dish. Rich in omega-3.",pro:8,carb:8,fat:5,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇵🇰",name:"Daal Chawal",origin:"Pakistan",tags:["lentils","rice cultures","onions","garlic","spices","yeast cultures"],why:"Complete protein combination. Cultural comfort across South Asia.",pro:8,carb:8,fat:2,vit:7,mealTypes:["breakfast","lunch","dinner"]},
  {flag:"🇳🇵",name:"Dal Bhat",origin:"Nepal",tags:["lentils","rice cultures","spinach","garlic","onions","spices"],why:"Sherpa staple. High-altitude endurance food repurposed for space.",pro:8,carb:8,fat:2,vit:9,mealTypes:["breakfast","lunch","dinner"]},
  {flag:"🇲🇾",name:"Nasi Lemak Bowl",origin:"Malaysia",tags:["rice cultures","algae milk","insect protein flour","seaweed sheets","seeds","onions"],why:"Aromatic coconut rice bowl. Cultural morale anchor for Southeast Asian crew.",pro:7,carb:8,fat:6,vit:7,mealTypes:["breakfast","lunch"]},
  {flag:"🇰🇪",name:"Ugali & Sukuma Wiki",origin:"Kenya",tags:["sweet potatoes","kale","soybeans","onions","algae oil","garlic"],why:"East African staple. Kale = dense micronutrient source.",pro:7,carb:8,fat:3,vit:10,mealTypes:["lunch","dinner"]},
  {flag:"🇿🇦",name:"Umngqusho",origin:"South Africa",tags:["soybeans","sweet potatoes","onions","garlic","bell peppers","seeds"],why:"Xhosa samp and beans dish. Complete plant protein pairing.",pro:8,carb:8,fat:3,vit:8,mealTypes:["lunch","dinner"]},
  {flag:"🇷🇺",name:"Buckwheat Kasha",origin:"Russia",tags:["quinoa","mushrooms","onions","algae oil","yeast cultures","seeds"],why:"Buckwheat substitute. High magnesium for muscle recovery.",pro:6,carb:8,fat:4,vit:8,mealTypes:["breakfast","lunch"]},
  {flag:"🇵🇱",name:"Żurek Soup",origin:"Poland",tags:["lentils","mycoprotein fungi","onions","garlic","yeast cultures","soybeans"],why:"Fermented rye soup adapted. Probiotic base for gut support.",pro:7,carb:6,fat:3,vit:8,mealTypes:["breakfast","lunch","dinner"]},
  {flag:"🇦🇪",name:"Harees",origin:"UAE / Gulf",tags:["oats","lab-grown chicken","onions","garlic","algae oil","spices"],why:"Ancient wheat-meat porridge. High calorie density for demanding shifts.",pro:8,carb:8,fat:4,vit:6,mealTypes:["breakfast","dinner"]},
  {flag:"🇲🇲",name:"Mohinga",origin:"Myanmar",tags:["algae noodles","cultured fish cells","lemongrass","onions","garlic","herbs"],why:"Myanmar's national breakfast. Warming fish noodle broth, immune support.",pro:7,carb:6,fat:4,vit:9,mealTypes:["breakfast","lunch"]},
];

const ING={
    protein: ["Soy Chunks", "Quorn", "Lentils"],
    carbs: ["Rice", "Oats", "Pasta"],
    fats: ["Olive Oil", "Nuts", "Avocado"],
    vitamins: ["Kale", "Spinach", "Carrots"],
    flavour: ["Garlic", "Soy Sauce", "Ginger"],
    hydration: ["Electrolyte Pack", "Coconut Water"]
};

const METHODS=[
  "Steam protein base · Roast root vegetables · Combine with mineral broth and seeds",
  "Boil grain base · Pan-sear protein with aromatics · Finish with algae oil and vitamin greens",
  "Simmer legumes with garlic and onions · Serve over grain · Top with omega-rich seeds",
  "Stir-fry protein and vegetables over high heat · Add fermented paste · Serve over rice base",
  "Blend protein and greens into a dense bowl · Drizzle with algae oil · Add grain crumble",
  "Slow-cook legume and vegetable broth · Fortify with mineral mix · Pair with grain base",
];